name: Debug with SSH (Persistent Artifacts)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      # 1. Download previous artifacts (if any exist)
      - name: Download previous artifacts
        uses: actions/download-artifact@v4
        with:
          name: debug-session-data
          path: ./data/
          if-no-files-found: warn  # Skip if no artifacts exist

      # 2. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 3. Start interactive SSH session
      - name: Start SSH session via tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          
      # 4. (After SSH ends) Upload new artifacts
      - name: Upload session artifacts
        if: always()  # Upload even if previous steps fail
        uses: actions/upload-artifact@v4
        with:
          name: debug-session-data
          path: |
            ./data/
            !**/node_modules  # Example: exclude node_modules
          retention-days: 90