name: Debug with SSH (Persistent Artifacts)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code first
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Download previous artifacts (with error handling)
      - name: Download previous artifacts
        id: download-artifact
        continue-on-error: true  # This prevents job failure if artifact doesn't exist
        uses: actions/download-artifact@v4
        with:
          name: debug-session-data
          path: ./data/

      # 3. Start SSH session
      - name: Start SSH session via tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
          timeout-minutes: 15
      # 4. Upload artifacts (even if previous steps fail)
      - name: Upload session artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-session-data
          path: ./data/
          retention-days: 7