name: Debug with SSH (Max 6h)
on:
  push:
    branches: [main]
  workflow_dispatch:
 
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start SSH session via tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true 
