name: Expose Exatorrent & Windows-KVM via Cloudflare

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  expose_services:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max (GitHub Free Tier)

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # ===== 1. Start Exatorrent (Node.js) =====
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and run Exatorrent
        working-directory: ./my-app
        run: |
          npm install
          npm run dev &
          sleep 5
          curl --retry 3 --retry-delay 2 http://localhost:3000 || echo "Exatorrent may not be ready"

      # ===== 2. Start Windows-KVM (Docker - KVM-less mode) =====
      - name: Setup Docker and Windows-KVM
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          
          # Run Windows-KVM in emulation mode (no KVM)
          docker run -d \
            --name windows \
            -p 8006:8006 \
            -e "DISABLE_KVM=1" \  # Force non-KVM mode
            -v "$PWD/windows:/storage" \
            --stop-timeout 120 \
            dockurr/windows

          # Wait for Windows web interface to start
          timeout 60 bash -c 'while ! curl -s http://localhost:8006 >/dev/null; do sleep 5; done' || \
            echo "Windows-KVM may be slow to start"

      # ===== 3. Verify Services Are Running =====
      - name: Check Services
        run: |
          echo "--- Running Containers ---"
          docker ps -a
          echo "--- Exatorrent Status ---"
          curl -I http://localhost:3000 || echo "Exatorrent not responding"
          echo "--- Windows-KVM Status ---"
          curl -I http://localhost:8006 || echo "Windows-KVM not responding"

      # ===== 4. Expose Services via Cloudflare =====
      - name: Setup cloudflared
        uses: AnimMouse/setup-cloudflared@v2

      - name: Expose Exatorrent (3000)
        uses: AnimMouse/setup-cloudflared/tunnel@v2
        with:
          url: http://localhost:3000
          tunnel-name: exatorrent-tunnel

      - name: Expose Windows-KVM (8006)
        uses: AnimMouse/setup-cloudflared/tunnel@v2
        with:
          url: http://localhost:8006
          tunnel-name: windows-tunnel

      # ===== 5. Show URLs and Keep Alive =====
      - name: Print Tunnel URLs
        run: |
          echo "Exatorrent URL: https://${EXATORRENT_TUNNEL_URL}"
          echo "Windows-KVM URL: https://${WINDOWS_TUNNEL_URL}"
          echo ""
          echo "Note: Windows-KVM may take 5-10 minutes to fully boot"
        env:
          EXATORRENT_TUNNEL_URL: ${{ steps.exatorrent-tunnel.outputs.url }}
          WINDOWS_TUNNEL_URL: ${{ steps.windows-tunnel.outputs.url }}

      - name: Keep alive (max 6h)
        run: |
          echo "Services will be available for 6 hours maximum"
          sleep 21600  # GitHub's maximum timeout