name: Expose Exatorrent & KasmWeb Desktop via Cloudflare

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  expose_services:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours max

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # ===== 1. Proper Docker Setup =====
      - name: Install Docker (correct way)
        run: |
          sudo apt-get remove -y containerd docker.io || true
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      # ===== 2. Start Exatorrent =====
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'


      # ===== 3. Start KasmWeb Desktop =====
      - name: Start KasmWeb Desktop
        run: |
          sudo systemctl start docker
          docker run -d \
            --name kasm-desktop \
            --shm-size=512m \
            -p 6901:6901 \
            -e VNC_PW=yourpassword \
            -e LANG=en_US.UTF-8 \
            -e LANGUAGE=en_US:en \
            kasmweb/desktop:1.14.0
          sleep 15
          docker logs kasm-desktop

      # ===== 4. Expose Services via Cloudflare =====
      - name: Setup cloudflared
        uses: AnimMouse/setup-cloudflared@v2


      - name: Expose KasmWeb Desktop (6901)
        uses: AnimMouse/setup-cloudflared/tunnel@v2
        with:
          url: http://localhost:6901
          tunnel-name: kasm-tunnel

      # ===== 5. Print URLs =====
      - name: Print Tunnel URLs
        run: |
          echo "Exatorrent URL: https://${EXATORRENT_TUNNEL_URL}"
          echo "KasmWeb Desktop URL: https://${KASM_TUNNEL_URL}"
          echo "Username: kasm_user"
          echo "Password: yourpassword"
        env:
          EXATORRENT_TUNNEL_URL: ${{ steps.exatorrent-tunnel.outputs.url }}
          KASM_TUNNEL_URL: ${{ steps.kasm-tunnel.outputs.url }}
        
      - name: List running Docker containers
        run: docker ps
        
      - name: Keep alive
        run: sleep 21600