name: Expose Exatorrent via Cloudflare Tunnel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  expose_exatorrent:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository first
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies and start the app
      - name: Install and run Exatorrent
        working-directory: ./my-app
        run: |
          npm install
          npm run dev &
          
          # Wait for server to start
          sleep 10
          curl --retry 3 --retry-delay 5 --retry-connrefused http://localhost:3000
          echo "Exatorrent server is running on port 3000"

      # Setup Cloudflare Tunnel
      - name: Setup cloudflared
        uses: AnimMouse/setup-cloudflared@v2
        
      - name: Expose Exatorrent via Cloudflare Tunnel
        uses: AnimMouse/setup-cloudflared/tunnel@v2
        with:
          url: http://localhost:3000  # Changed from 8080 to 3000 to match your app
          
      # Keep the workflow running to maintain the tunnel
      - name: Keep alive
        run: |
          echo "Tunnel is active - workflow will run for 30 minutes"
          sleep 1800  # 30 minutes
          
      # Shutdown and view logs
      - name: Shutdown and view logs of cloudflared
        if: '!cancelled()'
        uses: AnimMouse/setup-cloudflared/shutdown@v2