name: Check and Free Disk Space

on:
  push:
    branches:
      - main  # Trigger on push to main branch (adjust as needed)
  workflow_dispatch:  # Manually trigger from GitHub UI

jobs:
  disk_space:
    runs-on: ubuntu-latest  # You can change this to another runner if needed
    
    steps:
    - name: Free Disk Space (Ubuntu)
       uses: jlumbroso/free-disk-space@v1.3.1
