name: Install exatorrent on GitHub Actions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  install_exatorrent:
    runs-on: ubuntu-latest

    steps:
        # Run exatorrent in Docker with /mnt storage
      - name: Run exatorrent container
        run: |
          # Create a directory for exatorrent data in /mnt (where space is available)
          sudo mkdir -p /mnt/exatorrent/data
          sudo chown -R 1000:1000 /mnt/exatorrent/data  # Ensure container user can write

          # Run the container (port 5000, persistent storage in /mnt)
          docker run -d \
            --name exatorrent \
            -v /mnt/exatorrent/data:/app/data \
            -p 5000:5000 \
            varbhat/exatorrent

          # Verify it's running
          sleep 5
          curl -s http://localhost:5000 || echo "exatorrent may not be running"

      # Check disk space and container status
      - name: Verify setup
        run: |
          df -h
          docker ps
      
