name: Check and Free Disk Space

on:
  push:
    branches:
      - main  # Trigger on push to main branch (adjust as needed)
  workflow_dispatch:  # Manually trigger from GitHub UI

jobs:
  disk_space:
    runs-on: ubuntu-latest  # You can change this to another runner if needed
    
    steps:
    - name: Check initial disk space
      run: df -h
    
    - name: Free up disk space
      run: |
        echo "Cleaning up unnecessary files..."
        sudo apt-get remove -y '^ghc-.*' 'php.*' '^llvm-.*' '^dotnet-.*' '^mono-.*' '^android-.*'
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
    
    - name: Check available disk space after cleanup
      run: df -h
    
    - name: Verify available space with specific directories
      run: |
        echo "Listing files that might be taking up space:"
        du -sh /usr /opt /home/runner

